name: Run API tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest coverage

    - name: Start Flask API
      run: |
        nohup python app.py &
        sleep 5

    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage report
        coverage html

    - name: Upload coverage report
  uses: actions/upload-artifact@v3
  with:
    name: coverage-html
    path: htmlcov

